// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: trapperkeeper/sensor/v1/event.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	EventId string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// google.protobuf.Struct enables schema-agnostic JSON without predefined structure.
	// Rule engine queries Struct fields directly via field paths.
	Payload *structpb.Struct `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// String-only metadata enforces consistent type handling.
	// Complex metadata belongs in payload; metadata is for filtering/routing.
	Metadata        map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ClientTimestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=client_timestamp,json=clientTimestamp,proto3" json:"client_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_trapperkeeper_sensor_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_trapperkeeper_sensor_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_trapperkeeper_sensor_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Event) GetClientTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ClientTimestamp
	}
	return nil
}

var File_trapperkeeper_sensor_v1_event_proto protoreflect.FileDescriptor

const file_trapperkeeper_sensor_v1_event_proto_rawDesc = "" +
	"\n" +
	"#trapperkeeper/sensor/v1/event.proto\x12\x17trapperkeeper.sensor.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa3\x02\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x121\n" +
	"\apayload\x18\x02 \x01(\v2\x17.google.protobuf.StructR\apayload\x12H\n" +
	"\bmetadata\x18\x03 \x03(\v2,.trapperkeeper.sensor.v1.Event.MetadataEntryR\bmetadata\x12E\n" +
	"\x10client_timestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0fclientTimestamp\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\xf3\x01\n" +
	"\x1bcom.trapperkeeper.sensor.v1B\n" +
	"EventProtoP\x01ZJgithub.com/solatis/trapperkeeper/internal/protobuf/trapperkeeper/sensor/v1\xa2\x02\x03TSX\xaa\x02\x17Trapperkeeper.Sensor.V1\xca\x02\x17Trapperkeeper\\Sensor\\V1\xe2\x02#Trapperkeeper\\Sensor\\V1\\GPBMetadata\xea\x02\x19Trapperkeeper::Sensor::V1b\x06proto3"

var (
	file_trapperkeeper_sensor_v1_event_proto_rawDescOnce sync.Once
	file_trapperkeeper_sensor_v1_event_proto_rawDescData []byte
)

func file_trapperkeeper_sensor_v1_event_proto_rawDescGZIP() []byte {
	file_trapperkeeper_sensor_v1_event_proto_rawDescOnce.Do(func() {
		file_trapperkeeper_sensor_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trapperkeeper_sensor_v1_event_proto_rawDesc), len(file_trapperkeeper_sensor_v1_event_proto_rawDesc)))
	})
	return file_trapperkeeper_sensor_v1_event_proto_rawDescData
}

var file_trapperkeeper_sensor_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_trapperkeeper_sensor_v1_event_proto_goTypes = []any{
	(*Event)(nil),                 // 0: trapperkeeper.sensor.v1.Event
	nil,                           // 1: trapperkeeper.sensor.v1.Event.MetadataEntry
	(*structpb.Struct)(nil),       // 2: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_trapperkeeper_sensor_v1_event_proto_depIdxs = []int32{
	2, // 0: trapperkeeper.sensor.v1.Event.payload:type_name -> google.protobuf.Struct
	1, // 1: trapperkeeper.sensor.v1.Event.metadata:type_name -> trapperkeeper.sensor.v1.Event.MetadataEntry
	3, // 2: trapperkeeper.sensor.v1.Event.client_timestamp:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_trapperkeeper_sensor_v1_event_proto_init() }
func file_trapperkeeper_sensor_v1_event_proto_init() {
	if File_trapperkeeper_sensor_v1_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trapperkeeper_sensor_v1_event_proto_rawDesc), len(file_trapperkeeper_sensor_v1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trapperkeeper_sensor_v1_event_proto_goTypes,
		DependencyIndexes: file_trapperkeeper_sensor_v1_event_proto_depIdxs,
		MessageInfos:      file_trapperkeeper_sensor_v1_event_proto_msgTypes,
	}.Build()
	File_trapperkeeper_sensor_v1_event_proto = out.File
	file_trapperkeeper_sensor_v1_event_proto_goTypes = nil
	file_trapperkeeper_sensor_v1_event_proto_depIdxs = nil
}
