// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: trapperkeeper/sensor/v1/field_path.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FieldPath struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Segments      []*PathSegment         `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldPath) Reset() {
	*x = FieldPath{}
	mi := &file_trapperkeeper_sensor_v1_field_path_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldPath) ProtoMessage() {}

func (x *FieldPath) ProtoReflect() protoreflect.Message {
	mi := &file_trapperkeeper_sensor_v1_field_path_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldPath.ProtoReflect.Descriptor instead.
func (*FieldPath) Descriptor() ([]byte, []int) {
	return file_trapperkeeper_sensor_v1_field_path_proto_rawDescGZIP(), []int{0}
}

func (x *FieldPath) GetSegments() []*PathSegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

type PathSegment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// oneof enforces exactly-one-of constraint for segment types.
	// field_name: object property access ($.user)
	// array_index: array element access ($.items[0])
	// wildcard: match-all expansion ($.items[*])
	//
	// Types that are valid to be assigned to SegmentType:
	//
	//	*PathSegment_FieldName
	//	*PathSegment_ArrayIndex
	//	*PathSegment_Wildcard
	SegmentType   isPathSegment_SegmentType `protobuf_oneof:"segment_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathSegment) Reset() {
	*x = PathSegment{}
	mi := &file_trapperkeeper_sensor_v1_field_path_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathSegment) ProtoMessage() {}

func (x *PathSegment) ProtoReflect() protoreflect.Message {
	mi := &file_trapperkeeper_sensor_v1_field_path_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathSegment.ProtoReflect.Descriptor instead.
func (*PathSegment) Descriptor() ([]byte, []int) {
	return file_trapperkeeper_sensor_v1_field_path_proto_rawDescGZIP(), []int{1}
}

func (x *PathSegment) GetSegmentType() isPathSegment_SegmentType {
	if x != nil {
		return x.SegmentType
	}
	return nil
}

func (x *PathSegment) GetFieldName() string {
	if x != nil {
		if x, ok := x.SegmentType.(*PathSegment_FieldName); ok {
			return x.FieldName
		}
	}
	return ""
}

func (x *PathSegment) GetArrayIndex() int32 {
	if x != nil {
		if x, ok := x.SegmentType.(*PathSegment_ArrayIndex); ok {
			return x.ArrayIndex
		}
	}
	return 0
}

func (x *PathSegment) GetWildcard() *WildcardSegment {
	if x != nil {
		if x, ok := x.SegmentType.(*PathSegment_Wildcard); ok {
			return x.Wildcard
		}
	}
	return nil
}

type isPathSegment_SegmentType interface {
	isPathSegment_SegmentType()
}

type PathSegment_FieldName struct {
	FieldName string `protobuf:"bytes,1,opt,name=field_name,json=fieldName,proto3,oneof"`
}

type PathSegment_ArrayIndex struct {
	ArrayIndex int32 `protobuf:"varint,2,opt,name=array_index,json=arrayIndex,proto3,oneof"`
}

type PathSegment_Wildcard struct {
	Wildcard *WildcardSegment `protobuf:"bytes,3,opt,name=wildcard,proto3,oneof"`
}

func (*PathSegment_FieldName) isPathSegment_SegmentType() {}

func (*PathSegment_ArrayIndex) isPathSegment_SegmentType() {}

func (*PathSegment_Wildcard) isPathSegment_SegmentType() {}

// WildcardSegment represents a wildcard (*) in a field path.
// Empty message: proto3 oneof requires concrete types, not primitives.
// Presence indicates wildcard; no additional data needed.
type WildcardSegment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WildcardSegment) Reset() {
	*x = WildcardSegment{}
	mi := &file_trapperkeeper_sensor_v1_field_path_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WildcardSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WildcardSegment) ProtoMessage() {}

func (x *WildcardSegment) ProtoReflect() protoreflect.Message {
	mi := &file_trapperkeeper_sensor_v1_field_path_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WildcardSegment.ProtoReflect.Descriptor instead.
func (*WildcardSegment) Descriptor() ([]byte, []int) {
	return file_trapperkeeper_sensor_v1_field_path_proto_rawDescGZIP(), []int{2}
}

var File_trapperkeeper_sensor_v1_field_path_proto protoreflect.FileDescriptor

const file_trapperkeeper_sensor_v1_field_path_proto_rawDesc = "" +
	"\n" +
	"(trapperkeeper/sensor/v1/field_path.proto\x12\x17trapperkeeper.sensor.v1\"M\n" +
	"\tFieldPath\x12@\n" +
	"\bsegments\x18\x01 \x03(\v2$.trapperkeeper.sensor.v1.PathSegmentR\bsegments\"\xa9\x01\n" +
	"\vPathSegment\x12\x1f\n" +
	"\n" +
	"field_name\x18\x01 \x01(\tH\x00R\tfieldName\x12!\n" +
	"\varray_index\x18\x02 \x01(\x05H\x00R\n" +
	"arrayIndex\x12F\n" +
	"\bwildcard\x18\x03 \x01(\v2(.trapperkeeper.sensor.v1.WildcardSegmentH\x00R\bwildcardB\x0e\n" +
	"\fsegment_type\"\x11\n" +
	"\x0fWildcardSegmentB\xf7\x01\n" +
	"\x1bcom.trapperkeeper.sensor.v1B\x0eFieldPathProtoP\x01ZJgithub.com/solatis/trapperkeeper/internal/protobuf/trapperkeeper/sensor/v1\xa2\x02\x03TSX\xaa\x02\x17Trapperkeeper.Sensor.V1\xca\x02\x17Trapperkeeper\\Sensor\\V1\xe2\x02#Trapperkeeper\\Sensor\\V1\\GPBMetadata\xea\x02\x19Trapperkeeper::Sensor::V1b\x06proto3"

var (
	file_trapperkeeper_sensor_v1_field_path_proto_rawDescOnce sync.Once
	file_trapperkeeper_sensor_v1_field_path_proto_rawDescData []byte
)

func file_trapperkeeper_sensor_v1_field_path_proto_rawDescGZIP() []byte {
	file_trapperkeeper_sensor_v1_field_path_proto_rawDescOnce.Do(func() {
		file_trapperkeeper_sensor_v1_field_path_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trapperkeeper_sensor_v1_field_path_proto_rawDesc), len(file_trapperkeeper_sensor_v1_field_path_proto_rawDesc)))
	})
	return file_trapperkeeper_sensor_v1_field_path_proto_rawDescData
}

var file_trapperkeeper_sensor_v1_field_path_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_trapperkeeper_sensor_v1_field_path_proto_goTypes = []any{
	(*FieldPath)(nil),       // 0: trapperkeeper.sensor.v1.FieldPath
	(*PathSegment)(nil),     // 1: trapperkeeper.sensor.v1.PathSegment
	(*WildcardSegment)(nil), // 2: trapperkeeper.sensor.v1.WildcardSegment
}
var file_trapperkeeper_sensor_v1_field_path_proto_depIdxs = []int32{
	1, // 0: trapperkeeper.sensor.v1.FieldPath.segments:type_name -> trapperkeeper.sensor.v1.PathSegment
	2, // 1: trapperkeeper.sensor.v1.PathSegment.wildcard:type_name -> trapperkeeper.sensor.v1.WildcardSegment
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_trapperkeeper_sensor_v1_field_path_proto_init() }
func file_trapperkeeper_sensor_v1_field_path_proto_init() {
	if File_trapperkeeper_sensor_v1_field_path_proto != nil {
		return
	}
	file_trapperkeeper_sensor_v1_field_path_proto_msgTypes[1].OneofWrappers = []any{
		(*PathSegment_FieldName)(nil),
		(*PathSegment_ArrayIndex)(nil),
		(*PathSegment_Wildcard)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trapperkeeper_sensor_v1_field_path_proto_rawDesc), len(file_trapperkeeper_sensor_v1_field_path_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trapperkeeper_sensor_v1_field_path_proto_goTypes,
		DependencyIndexes: file_trapperkeeper_sensor_v1_field_path_proto_depIdxs,
		MessageInfos:      file_trapperkeeper_sensor_v1_field_path_proto_msgTypes,
	}.Build()
	File_trapperkeeper_sensor_v1_field_path_proto = out.File
	file_trapperkeeper_sensor_v1_field_path_proto_goTypes = nil
	file_trapperkeeper_sensor_v1_field_path_proto_depIdxs = nil
}
