// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: trapperkeeper/sensor/v1/rule.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NullValue int32

const (
	NullValue_NULL_VALUE_UNSPECIFIED NullValue = 0
)

// Enum value maps for NullValue.
var (
	NullValue_name = map[int32]string{
		0: "NULL_VALUE_UNSPECIFIED",
	}
	NullValue_value = map[string]int32{
		"NULL_VALUE_UNSPECIFIED": 0,
	}
)

func (x NullValue) Enum() *NullValue {
	p := new(NullValue)
	*p = x
	return p
}

func (x NullValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NullValue) Descriptor() protoreflect.EnumDescriptor {
	return file_trapperkeeper_sensor_v1_rule_proto_enumTypes[0].Descriptor()
}

func (NullValue) Type() protoreflect.EnumType {
	return &file_trapperkeeper_sensor_v1_rule_proto_enumTypes[0]
}

func (x NullValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NullValue.Descriptor instead.
func (NullValue) EnumDescriptor() ([]byte, []int) {
	return file_trapperkeeper_sensor_v1_rule_proto_rawDescGZIP(), []int{0}
}

type Operator int32

const (
	Operator_OPERATOR_UNSPECIFIED Operator = 0
	Operator_OPERATOR_EQ          Operator = 1
	Operator_OPERATOR_NEQ         Operator = 2
	Operator_OPERATOR_LT          Operator = 3
	Operator_OPERATOR_LTE         Operator = 4
	Operator_OPERATOR_GT          Operator = 5
	Operator_OPERATOR_GTE         Operator = 6
	Operator_OPERATOR_PREFIX      Operator = 7
	Operator_OPERATOR_SUFFIX      Operator = 8
	Operator_OPERATOR_CONTAINS    Operator = 9
	Operator_OPERATOR_IN          Operator = 10
	Operator_OPERATOR_EXISTS      Operator = 11
	Operator_OPERATOR_IS_NULL     Operator = 12
)

// Enum value maps for Operator.
var (
	Operator_name = map[int32]string{
		0:  "OPERATOR_UNSPECIFIED",
		1:  "OPERATOR_EQ",
		2:  "OPERATOR_NEQ",
		3:  "OPERATOR_LT",
		4:  "OPERATOR_LTE",
		5:  "OPERATOR_GT",
		6:  "OPERATOR_GTE",
		7:  "OPERATOR_PREFIX",
		8:  "OPERATOR_SUFFIX",
		9:  "OPERATOR_CONTAINS",
		10: "OPERATOR_IN",
		11: "OPERATOR_EXISTS",
		12: "OPERATOR_IS_NULL",
	}
	Operator_value = map[string]int32{
		"OPERATOR_UNSPECIFIED": 0,
		"OPERATOR_EQ":          1,
		"OPERATOR_NEQ":         2,
		"OPERATOR_LT":          3,
		"OPERATOR_LTE":         4,
		"OPERATOR_GT":          5,
		"OPERATOR_GTE":         6,
		"OPERATOR_PREFIX":      7,
		"OPERATOR_SUFFIX":      8,
		"OPERATOR_CONTAINS":    9,
		"OPERATOR_IN":          10,
		"OPERATOR_EXISTS":      11,
		"OPERATOR_IS_NULL":     12,
	}
)

func (x Operator) Enum() *Operator {
	p := new(Operator)
	*p = x
	return p
}

func (x Operator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operator) Descriptor() protoreflect.EnumDescriptor {
	return file_trapperkeeper_sensor_v1_rule_proto_enumTypes[1].Descriptor()
}

func (Operator) Type() protoreflect.EnumType {
	return &file_trapperkeeper_sensor_v1_rule_proto_enumTypes[1]
}

func (x Operator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operator.Descriptor instead.
func (Operator) EnumDescriptor() ([]byte, []int) {
	return file_trapperkeeper_sensor_v1_rule_proto_rawDescGZIP(), []int{1}
}

type FieldType int32

const (
	FieldType_FIELD_TYPE_UNSPECIFIED FieldType = 0
	FieldType_FIELD_TYPE_NUMERIC     FieldType = 1
	FieldType_FIELD_TYPE_TEXT        FieldType = 2
	FieldType_FIELD_TYPE_BOOLEAN     FieldType = 3
	FieldType_FIELD_TYPE_ANY         FieldType = 4
)

// Enum value maps for FieldType.
var (
	FieldType_name = map[int32]string{
		0: "FIELD_TYPE_UNSPECIFIED",
		1: "FIELD_TYPE_NUMERIC",
		2: "FIELD_TYPE_TEXT",
		3: "FIELD_TYPE_BOOLEAN",
		4: "FIELD_TYPE_ANY",
	}
	FieldType_value = map[string]int32{
		"FIELD_TYPE_UNSPECIFIED": 0,
		"FIELD_TYPE_NUMERIC":     1,
		"FIELD_TYPE_TEXT":        2,
		"FIELD_TYPE_BOOLEAN":     3,
		"FIELD_TYPE_ANY":         4,
	}
)

func (x FieldType) Enum() *FieldType {
	p := new(FieldType)
	*p = x
	return p
}

func (x FieldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldType) Descriptor() protoreflect.EnumDescriptor {
	return file_trapperkeeper_sensor_v1_rule_proto_enumTypes[2].Descriptor()
}

func (FieldType) Type() protoreflect.EnumType {
	return &file_trapperkeeper_sensor_v1_rule_proto_enumTypes[2]
}

func (x FieldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FieldType.Descriptor instead.
func (FieldType) EnumDescriptor() ([]byte, []int) {
	return file_trapperkeeper_sensor_v1_rule_proto_rawDescGZIP(), []int{2}
}

type RuleState int32

const (
	RuleState_RULE_STATE_UNSPECIFIED RuleState = 0
	RuleState_RULE_STATE_DRAFT       RuleState = 1
	RuleState_RULE_STATE_ACTIVE      RuleState = 2
	RuleState_RULE_STATE_DISABLED    RuleState = 3
)

// Enum value maps for RuleState.
var (
	RuleState_name = map[int32]string{
		0: "RULE_STATE_UNSPECIFIED",
		1: "RULE_STATE_DRAFT",
		2: "RULE_STATE_ACTIVE",
		3: "RULE_STATE_DISABLED",
	}
	RuleState_value = map[string]int32{
		"RULE_STATE_UNSPECIFIED": 0,
		"RULE_STATE_DRAFT":       1,
		"RULE_STATE_ACTIVE":      2,
		"RULE_STATE_DISABLED":    3,
	}
)

func (x RuleState) Enum() *RuleState {
	p := new(RuleState)
	*p = x
	return p
}

func (x RuleState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuleState) Descriptor() protoreflect.EnumDescriptor {
	return file_trapperkeeper_sensor_v1_rule_proto_enumTypes[3].Descriptor()
}

func (RuleState) Type() protoreflect.EnumType {
	return &file_trapperkeeper_sensor_v1_rule_proto_enumTypes[3]
}

func (x RuleState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuleState.Descriptor instead.
func (RuleState) EnumDescriptor() ([]byte, []int) {
	return file_trapperkeeper_sensor_v1_rule_proto_rawDescGZIP(), []int{3}
}

type Action int32

const (
	Action_ACTION_UNSPECIFIED Action = 0
	Action_ACTION_OBSERVE     Action = 1
	Action_ACTION_DROP        Action = 2
	Action_ACTION_FAIL        Action = 3
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_OBSERVE",
		2: "ACTION_DROP",
		3: "ACTION_FAIL",
	}
	Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_OBSERVE":     1,
		"ACTION_DROP":        2,
		"ACTION_FAIL":        3,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_trapperkeeper_sensor_v1_rule_proto_enumTypes[4].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_trapperkeeper_sensor_v1_rule_proto_enumTypes[4]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_trapperkeeper_sensor_v1_rule_proto_rawDescGZIP(), []int{4}
}

type OnMissingField int32

const (
	OnMissingField_ON_MISSING_FIELD_UNSPECIFIED OnMissingField = 0
	OnMissingField_ON_MISSING_FIELD_SKIP        OnMissingField = 1
	OnMissingField_ON_MISSING_FIELD_MATCH       OnMissingField = 2
	OnMissingField_ON_MISSING_FIELD_FAIL        OnMissingField = 3
)

// Enum value maps for OnMissingField.
var (
	OnMissingField_name = map[int32]string{
		0: "ON_MISSING_FIELD_UNSPECIFIED",
		1: "ON_MISSING_FIELD_SKIP",
		2: "ON_MISSING_FIELD_MATCH",
		3: "ON_MISSING_FIELD_FAIL",
	}
	OnMissingField_value = map[string]int32{
		"ON_MISSING_FIELD_UNSPECIFIED": 0,
		"ON_MISSING_FIELD_SKIP":        1,
		"ON_MISSING_FIELD_MATCH":       2,
		"ON_MISSING_FIELD_FAIL":        3,
	}
)

func (x OnMissingField) Enum() *OnMissingField {
	p := new(OnMissingField)
	*p = x
	return p
}

func (x OnMissingField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OnMissingField) Descriptor() protoreflect.EnumDescriptor {
	return file_trapperkeeper_sensor_v1_rule_proto_enumTypes[5].Descriptor()
}

func (OnMissingField) Type() protoreflect.EnumType {
	return &file_trapperkeeper_sensor_v1_rule_proto_enumTypes[5]
}

func (x OnMissingField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OnMissingField.Descriptor instead.
func (OnMissingField) EnumDescriptor() ([]byte, []int) {
	return file_trapperkeeper_sensor_v1_rule_proto_rawDescGZIP(), []int{5}
}

type OnCoercionFail int32

const (
	OnCoercionFail_ON_COERCION_FAIL_UNSPECIFIED OnCoercionFail = 0
	OnCoercionFail_ON_COERCION_FAIL_SKIP        OnCoercionFail = 1
	OnCoercionFail_ON_COERCION_FAIL_MATCH       OnCoercionFail = 2
	OnCoercionFail_ON_COERCION_FAIL_FAIL        OnCoercionFail = 3
)

// Enum value maps for OnCoercionFail.
var (
	OnCoercionFail_name = map[int32]string{
		0: "ON_COERCION_FAIL_UNSPECIFIED",
		1: "ON_COERCION_FAIL_SKIP",
		2: "ON_COERCION_FAIL_MATCH",
		3: "ON_COERCION_FAIL_FAIL",
	}
	OnCoercionFail_value = map[string]int32{
		"ON_COERCION_FAIL_UNSPECIFIED": 0,
		"ON_COERCION_FAIL_SKIP":        1,
		"ON_COERCION_FAIL_MATCH":       2,
		"ON_COERCION_FAIL_FAIL":        3,
	}
)

func (x OnCoercionFail) Enum() *OnCoercionFail {
	p := new(OnCoercionFail)
	*p = x
	return p
}

func (x OnCoercionFail) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OnCoercionFail) Descriptor() protoreflect.EnumDescriptor {
	return file_trapperkeeper_sensor_v1_rule_proto_enumTypes[6].Descriptor()
}

func (OnCoercionFail) Type() protoreflect.EnumType {
	return &file_trapperkeeper_sensor_v1_rule_proto_enumTypes[6]
}

func (x OnCoercionFail) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OnCoercionFail.Descriptor instead.
func (OnCoercionFail) EnumDescriptor() ([]byte, []int) {
	return file_trapperkeeper_sensor_v1_rule_proto_rawDescGZIP(), []int{6}
}

type Rule struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	RuleId string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Name   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	State  RuleState              `protobuf:"varint,3,opt,name=state,proto3,enum=trapperkeeper.sensor.v1.RuleState" json:"state,omitempty"`
	Action Action                 `protobuf:"varint,4,opt,name=action,proto3,enum=trapperkeeper.sensor.v1.Action" json:"action,omitempty"`
	// or_groups encodes DNF (Disjunctive Normal Form): OR of ANDs.
	// Each OrGroup is an AND of Conditions; groups are ORed together.
	// Empty list matches nothing (invalid rule).
	OrGroups []*OrGroup `protobuf:"bytes,5,rep,name=or_groups,json=orGroups,proto3" json:"or_groups,omitempty"`
	// sample_rate enables probabilistic evaluation (0.0 = never, 1.0 = always).
	// Values outside [0.0, 1.0] are invalid; callers must validate before use.
	SampleRate    float64                `protobuf:"fixed64,6,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	ScopeTags     []*ScopeTag            `protobuf:"bytes,7,rep,name=scope_tags,json=scopeTags,proto3" json:"scope_tags,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_trapperkeeper_sensor_v1_rule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_trapperkeeper_sensor_v1_rule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_trapperkeeper_sensor_v1_rule_proto_rawDescGZIP(), []int{0}
}

func (x *Rule) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *Rule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Rule) GetState() RuleState {
	if x != nil {
		return x.State
	}
	return RuleState_RULE_STATE_UNSPECIFIED
}

func (x *Rule) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_UNSPECIFIED
}

func (x *Rule) GetOrGroups() []*OrGroup {
	if x != nil {
		return x.OrGroups
	}
	return nil
}

func (x *Rule) GetSampleRate() float64 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *Rule) GetScopeTags() []*ScopeTag {
	if x != nil {
		return x.ScopeTags
	}
	return nil
}

func (x *Rule) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type OrGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupIndex    int32                  `protobuf:"varint,1,opt,name=group_index,json=groupIndex,proto3" json:"group_index,omitempty"`
	Conditions    []*Condition           `protobuf:"bytes,2,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrGroup) Reset() {
	*x = OrGroup{}
	mi := &file_trapperkeeper_sensor_v1_rule_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrGroup) ProtoMessage() {}

func (x *OrGroup) ProtoReflect() protoreflect.Message {
	mi := &file_trapperkeeper_sensor_v1_rule_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrGroup.ProtoReflect.Descriptor instead.
func (*OrGroup) Descriptor() ([]byte, []int) {
	return file_trapperkeeper_sensor_v1_rule_proto_rawDescGZIP(), []int{1}
}

func (x *OrGroup) GetGroupIndex() int32 {
	if x != nil {
		return x.GroupIndex
	}
	return 0
}

func (x *OrGroup) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type Condition struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FieldPath      *FieldPath             `protobuf:"bytes,1,opt,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	Op             Operator               `protobuf:"varint,2,opt,name=op,proto3,enum=trapperkeeper.sensor.v1.Operator" json:"op,omitempty"`
	Value          *ConditionValue        `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	FieldType      FieldType              `protobuf:"varint,4,opt,name=field_type,json=fieldType,proto3,enum=trapperkeeper.sensor.v1.FieldType" json:"field_type,omitempty"`
	OnMissingField OnMissingField         `protobuf:"varint,5,opt,name=on_missing_field,json=onMissingField,proto3,enum=trapperkeeper.sensor.v1.OnMissingField" json:"on_missing_field,omitempty"`
	OnCoercionFail OnCoercionFail         `protobuf:"varint,6,opt,name=on_coercion_fail,json=onCoercionFail,proto3,enum=trapperkeeper.sensor.v1.OnCoercionFail" json:"on_coercion_fail,omitempty"`
	// field_ref enables cross-field comparison ($.price < $.budget).
	// When set, compare field_path against field_ref instead of value.
	// Mutually exclusive with value; setting both is invalid.
	FieldRef      *FieldPath `protobuf:"bytes,7,opt,name=field_ref,json=fieldRef,proto3" json:"field_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_trapperkeeper_sensor_v1_rule_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_trapperkeeper_sensor_v1_rule_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_trapperkeeper_sensor_v1_rule_proto_rawDescGZIP(), []int{2}
}

func (x *Condition) GetFieldPath() *FieldPath {
	if x != nil {
		return x.FieldPath
	}
	return nil
}

func (x *Condition) GetOp() Operator {
	if x != nil {
		return x.Op
	}
	return Operator_OPERATOR_UNSPECIFIED
}

func (x *Condition) GetValue() *ConditionValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Condition) GetFieldType() FieldType {
	if x != nil {
		return x.FieldType
	}
	return FieldType_FIELD_TYPE_UNSPECIFIED
}

func (x *Condition) GetOnMissingField() OnMissingField {
	if x != nil {
		return x.OnMissingField
	}
	return OnMissingField_ON_MISSING_FIELD_UNSPECIFIED
}

func (x *Condition) GetOnCoercionFail() OnCoercionFail {
	if x != nil {
		return x.OnCoercionFail
	}
	return OnCoercionFail_ON_COERCION_FAIL_UNSPECIFIED
}

func (x *Condition) GetFieldRef() *FieldPath {
	if x != nil {
		return x.FieldRef
	}
	return nil
}

type ConditionValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// oneof enables type-safe value representation without runtime type inspection.
	// Arrays support IN operator; null_value supports IS_NULL/EXISTS operators.
	//
	// Types that are valid to be assigned to ValueType:
	//
	//	*ConditionValue_StringValue
	//	*ConditionValue_NumericValue
	//	*ConditionValue_BooleanValue
	//	*ConditionValue_NullValue
	//	*ConditionValue_StringArray
	//	*ConditionValue_NumericArray
	ValueType     isConditionValue_ValueType `protobuf_oneof:"value_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConditionValue) Reset() {
	*x = ConditionValue{}
	mi := &file_trapperkeeper_sensor_v1_rule_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConditionValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionValue) ProtoMessage() {}

func (x *ConditionValue) ProtoReflect() protoreflect.Message {
	mi := &file_trapperkeeper_sensor_v1_rule_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionValue.ProtoReflect.Descriptor instead.
func (*ConditionValue) Descriptor() ([]byte, []int) {
	return file_trapperkeeper_sensor_v1_rule_proto_rawDescGZIP(), []int{3}
}

func (x *ConditionValue) GetValueType() isConditionValue_ValueType {
	if x != nil {
		return x.ValueType
	}
	return nil
}

func (x *ConditionValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.ValueType.(*ConditionValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *ConditionValue) GetNumericValue() float64 {
	if x != nil {
		if x, ok := x.ValueType.(*ConditionValue_NumericValue); ok {
			return x.NumericValue
		}
	}
	return 0
}

func (x *ConditionValue) GetBooleanValue() bool {
	if x != nil {
		if x, ok := x.ValueType.(*ConditionValue_BooleanValue); ok {
			return x.BooleanValue
		}
	}
	return false
}

func (x *ConditionValue) GetNullValue() NullValue {
	if x != nil {
		if x, ok := x.ValueType.(*ConditionValue_NullValue); ok {
			return x.NullValue
		}
	}
	return NullValue_NULL_VALUE_UNSPECIFIED
}

func (x *ConditionValue) GetStringArray() *StringArray {
	if x != nil {
		if x, ok := x.ValueType.(*ConditionValue_StringArray); ok {
			return x.StringArray
		}
	}
	return nil
}

func (x *ConditionValue) GetNumericArray() *NumericArray {
	if x != nil {
		if x, ok := x.ValueType.(*ConditionValue_NumericArray); ok {
			return x.NumericArray
		}
	}
	return nil
}

type isConditionValue_ValueType interface {
	isConditionValue_ValueType()
}

type ConditionValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type ConditionValue_NumericValue struct {
	NumericValue float64 `protobuf:"fixed64,2,opt,name=numeric_value,json=numericValue,proto3,oneof"`
}

type ConditionValue_BooleanValue struct {
	BooleanValue bool `protobuf:"varint,3,opt,name=boolean_value,json=booleanValue,proto3,oneof"`
}

type ConditionValue_NullValue struct {
	NullValue NullValue `protobuf:"varint,4,opt,name=null_value,json=nullValue,proto3,enum=trapperkeeper.sensor.v1.NullValue,oneof"`
}

type ConditionValue_StringArray struct {
	StringArray *StringArray `protobuf:"bytes,5,opt,name=string_array,json=stringArray,proto3,oneof"`
}

type ConditionValue_NumericArray struct {
	NumericArray *NumericArray `protobuf:"bytes,6,opt,name=numeric_array,json=numericArray,proto3,oneof"`
}

func (*ConditionValue_StringValue) isConditionValue_ValueType() {}

func (*ConditionValue_NumericValue) isConditionValue_ValueType() {}

func (*ConditionValue_BooleanValue) isConditionValue_ValueType() {}

func (*ConditionValue_NullValue) isConditionValue_ValueType() {}

func (*ConditionValue_StringArray) isConditionValue_ValueType() {}

func (*ConditionValue_NumericArray) isConditionValue_ValueType() {}

type StringArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringArray) Reset() {
	*x = StringArray{}
	mi := &file_trapperkeeper_sensor_v1_rule_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringArray) ProtoMessage() {}

func (x *StringArray) ProtoReflect() protoreflect.Message {
	mi := &file_trapperkeeper_sensor_v1_rule_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringArray.ProtoReflect.Descriptor instead.
func (*StringArray) Descriptor() ([]byte, []int) {
	return file_trapperkeeper_sensor_v1_rule_proto_rawDescGZIP(), []int{4}
}

func (x *StringArray) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type NumericArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float64              `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumericArray) Reset() {
	*x = NumericArray{}
	mi := &file_trapperkeeper_sensor_v1_rule_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumericArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumericArray) ProtoMessage() {}

func (x *NumericArray) ProtoReflect() protoreflect.Message {
	mi := &file_trapperkeeper_sensor_v1_rule_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumericArray.ProtoReflect.Descriptor instead.
func (*NumericArray) Descriptor() ([]byte, []int) {
	return file_trapperkeeper_sensor_v1_rule_proto_rawDescGZIP(), []int{5}
}

func (x *NumericArray) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type ScopeTag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScopeTag) Reset() {
	*x = ScopeTag{}
	mi := &file_trapperkeeper_sensor_v1_rule_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScopeTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopeTag) ProtoMessage() {}

func (x *ScopeTag) ProtoReflect() protoreflect.Message {
	mi := &file_trapperkeeper_sensor_v1_rule_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopeTag.ProtoReflect.Descriptor instead.
func (*ScopeTag) Descriptor() ([]byte, []int) {
	return file_trapperkeeper_sensor_v1_rule_proto_rawDescGZIP(), []int{6}
}

func (x *ScopeTag) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ScopeTag) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_trapperkeeper_sensor_v1_rule_proto protoreflect.FileDescriptor

const file_trapperkeeper_sensor_v1_rule_proto_rawDesc = "" +
	"\n" +
	"\"trapperkeeper/sensor/v1/rule.proto\x12\x17trapperkeeper.sensor.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a(trapperkeeper/sensor/v1/field_path.proto\"\x83\x03\n" +
	"\x04Rule\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x128\n" +
	"\x05state\x18\x03 \x01(\x0e2\".trapperkeeper.sensor.v1.RuleStateR\x05state\x127\n" +
	"\x06action\x18\x04 \x01(\x0e2\x1f.trapperkeeper.sensor.v1.ActionR\x06action\x12=\n" +
	"\tor_groups\x18\x05 \x03(\v2 .trapperkeeper.sensor.v1.OrGroupR\borGroups\x12\x1f\n" +
	"\vsample_rate\x18\x06 \x01(\x01R\n" +
	"sampleRate\x12@\n" +
	"\n" +
	"scope_tags\x18\a \x03(\v2!.trapperkeeper.sensor.v1.ScopeTagR\tscopeTags\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"n\n" +
	"\aOrGroup\x12\x1f\n" +
	"\vgroup_index\x18\x01 \x01(\x05R\n" +
	"groupIndex\x12B\n" +
	"\n" +
	"conditions\x18\x02 \x03(\v2\".trapperkeeper.sensor.v1.ConditionR\n" +
	"conditions\"\xea\x03\n" +
	"\tCondition\x12A\n" +
	"\n" +
	"field_path\x18\x01 \x01(\v2\".trapperkeeper.sensor.v1.FieldPathR\tfieldPath\x121\n" +
	"\x02op\x18\x02 \x01(\x0e2!.trapperkeeper.sensor.v1.OperatorR\x02op\x12=\n" +
	"\x05value\x18\x03 \x01(\v2'.trapperkeeper.sensor.v1.ConditionValueR\x05value\x12A\n" +
	"\n" +
	"field_type\x18\x04 \x01(\x0e2\".trapperkeeper.sensor.v1.FieldTypeR\tfieldType\x12Q\n" +
	"\x10on_missing_field\x18\x05 \x01(\x0e2'.trapperkeeper.sensor.v1.OnMissingFieldR\x0eonMissingField\x12Q\n" +
	"\x10on_coercion_fail\x18\x06 \x01(\x0e2'.trapperkeeper.sensor.v1.OnCoercionFailR\x0eonCoercionFail\x12?\n" +
	"\tfield_ref\x18\a \x01(\v2\".trapperkeeper.sensor.v1.FieldPathR\bfieldRef\"\xef\x02\n" +
	"\x0eConditionValue\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12%\n" +
	"\rnumeric_value\x18\x02 \x01(\x01H\x00R\fnumericValue\x12%\n" +
	"\rboolean_value\x18\x03 \x01(\bH\x00R\fbooleanValue\x12C\n" +
	"\n" +
	"null_value\x18\x04 \x01(\x0e2\".trapperkeeper.sensor.v1.NullValueH\x00R\tnullValue\x12I\n" +
	"\fstring_array\x18\x05 \x01(\v2$.trapperkeeper.sensor.v1.StringArrayH\x00R\vstringArray\x12L\n" +
	"\rnumeric_array\x18\x06 \x01(\v2%.trapperkeeper.sensor.v1.NumericArrayH\x00R\fnumericArrayB\f\n" +
	"\n" +
	"value_type\"%\n" +
	"\vStringArray\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"&\n" +
	"\fNumericArray\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x01R\x06values\"2\n" +
	"\bScopeTag\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value*'\n" +
	"\tNullValue\x12\x1a\n" +
	"\x16NULL_VALUE_UNSPECIFIED\x10\x00*\x8a\x02\n" +
	"\bOperator\x12\x18\n" +
	"\x14OPERATOR_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vOPERATOR_EQ\x10\x01\x12\x10\n" +
	"\fOPERATOR_NEQ\x10\x02\x12\x0f\n" +
	"\vOPERATOR_LT\x10\x03\x12\x10\n" +
	"\fOPERATOR_LTE\x10\x04\x12\x0f\n" +
	"\vOPERATOR_GT\x10\x05\x12\x10\n" +
	"\fOPERATOR_GTE\x10\x06\x12\x13\n" +
	"\x0fOPERATOR_PREFIX\x10\a\x12\x13\n" +
	"\x0fOPERATOR_SUFFIX\x10\b\x12\x15\n" +
	"\x11OPERATOR_CONTAINS\x10\t\x12\x0f\n" +
	"\vOPERATOR_IN\x10\n" +
	"\x12\x13\n" +
	"\x0fOPERATOR_EXISTS\x10\v\x12\x14\n" +
	"\x10OPERATOR_IS_NULL\x10\f*\x80\x01\n" +
	"\tFieldType\x12\x1a\n" +
	"\x16FIELD_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12FIELD_TYPE_NUMERIC\x10\x01\x12\x13\n" +
	"\x0fFIELD_TYPE_TEXT\x10\x02\x12\x16\n" +
	"\x12FIELD_TYPE_BOOLEAN\x10\x03\x12\x12\n" +
	"\x0eFIELD_TYPE_ANY\x10\x04*m\n" +
	"\tRuleState\x12\x1a\n" +
	"\x16RULE_STATE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10RULE_STATE_DRAFT\x10\x01\x12\x15\n" +
	"\x11RULE_STATE_ACTIVE\x10\x02\x12\x17\n" +
	"\x13RULE_STATE_DISABLED\x10\x03*V\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eACTION_OBSERVE\x10\x01\x12\x0f\n" +
	"\vACTION_DROP\x10\x02\x12\x0f\n" +
	"\vACTION_FAIL\x10\x03*\x84\x01\n" +
	"\x0eOnMissingField\x12 \n" +
	"\x1cON_MISSING_FIELD_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ON_MISSING_FIELD_SKIP\x10\x01\x12\x1a\n" +
	"\x16ON_MISSING_FIELD_MATCH\x10\x02\x12\x19\n" +
	"\x15ON_MISSING_FIELD_FAIL\x10\x03*\x84\x01\n" +
	"\x0eOnCoercionFail\x12 \n" +
	"\x1cON_COERCION_FAIL_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ON_COERCION_FAIL_SKIP\x10\x01\x12\x1a\n" +
	"\x16ON_COERCION_FAIL_MATCH\x10\x02\x12\x19\n" +
	"\x15ON_COERCION_FAIL_FAIL\x10\x03B\xf2\x01\n" +
	"\x1bcom.trapperkeeper.sensor.v1B\tRuleProtoP\x01ZJgithub.com/solatis/trapperkeeper/internal/protobuf/trapperkeeper/sensor/v1\xa2\x02\x03TSX\xaa\x02\x17Trapperkeeper.Sensor.V1\xca\x02\x17Trapperkeeper\\Sensor\\V1\xe2\x02#Trapperkeeper\\Sensor\\V1\\GPBMetadata\xea\x02\x19Trapperkeeper::Sensor::V1b\x06proto3"

var (
	file_trapperkeeper_sensor_v1_rule_proto_rawDescOnce sync.Once
	file_trapperkeeper_sensor_v1_rule_proto_rawDescData []byte
)

func file_trapperkeeper_sensor_v1_rule_proto_rawDescGZIP() []byte {
	file_trapperkeeper_sensor_v1_rule_proto_rawDescOnce.Do(func() {
		file_trapperkeeper_sensor_v1_rule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trapperkeeper_sensor_v1_rule_proto_rawDesc), len(file_trapperkeeper_sensor_v1_rule_proto_rawDesc)))
	})
	return file_trapperkeeper_sensor_v1_rule_proto_rawDescData
}

var file_trapperkeeper_sensor_v1_rule_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_trapperkeeper_sensor_v1_rule_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_trapperkeeper_sensor_v1_rule_proto_goTypes = []any{
	(NullValue)(0),                // 0: trapperkeeper.sensor.v1.NullValue
	(Operator)(0),                 // 1: trapperkeeper.sensor.v1.Operator
	(FieldType)(0),                // 2: trapperkeeper.sensor.v1.FieldType
	(RuleState)(0),                // 3: trapperkeeper.sensor.v1.RuleState
	(Action)(0),                   // 4: trapperkeeper.sensor.v1.Action
	(OnMissingField)(0),           // 5: trapperkeeper.sensor.v1.OnMissingField
	(OnCoercionFail)(0),           // 6: trapperkeeper.sensor.v1.OnCoercionFail
	(*Rule)(nil),                  // 7: trapperkeeper.sensor.v1.Rule
	(*OrGroup)(nil),               // 8: trapperkeeper.sensor.v1.OrGroup
	(*Condition)(nil),             // 9: trapperkeeper.sensor.v1.Condition
	(*ConditionValue)(nil),        // 10: trapperkeeper.sensor.v1.ConditionValue
	(*StringArray)(nil),           // 11: trapperkeeper.sensor.v1.StringArray
	(*NumericArray)(nil),          // 12: trapperkeeper.sensor.v1.NumericArray
	(*ScopeTag)(nil),              // 13: trapperkeeper.sensor.v1.ScopeTag
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
	(*FieldPath)(nil),             // 15: trapperkeeper.sensor.v1.FieldPath
}
var file_trapperkeeper_sensor_v1_rule_proto_depIdxs = []int32{
	3,  // 0: trapperkeeper.sensor.v1.Rule.state:type_name -> trapperkeeper.sensor.v1.RuleState
	4,  // 1: trapperkeeper.sensor.v1.Rule.action:type_name -> trapperkeeper.sensor.v1.Action
	8,  // 2: trapperkeeper.sensor.v1.Rule.or_groups:type_name -> trapperkeeper.sensor.v1.OrGroup
	13, // 3: trapperkeeper.sensor.v1.Rule.scope_tags:type_name -> trapperkeeper.sensor.v1.ScopeTag
	14, // 4: trapperkeeper.sensor.v1.Rule.created_at:type_name -> google.protobuf.Timestamp
	9,  // 5: trapperkeeper.sensor.v1.OrGroup.conditions:type_name -> trapperkeeper.sensor.v1.Condition
	15, // 6: trapperkeeper.sensor.v1.Condition.field_path:type_name -> trapperkeeper.sensor.v1.FieldPath
	1,  // 7: trapperkeeper.sensor.v1.Condition.op:type_name -> trapperkeeper.sensor.v1.Operator
	10, // 8: trapperkeeper.sensor.v1.Condition.value:type_name -> trapperkeeper.sensor.v1.ConditionValue
	2,  // 9: trapperkeeper.sensor.v1.Condition.field_type:type_name -> trapperkeeper.sensor.v1.FieldType
	5,  // 10: trapperkeeper.sensor.v1.Condition.on_missing_field:type_name -> trapperkeeper.sensor.v1.OnMissingField
	6,  // 11: trapperkeeper.sensor.v1.Condition.on_coercion_fail:type_name -> trapperkeeper.sensor.v1.OnCoercionFail
	15, // 12: trapperkeeper.sensor.v1.Condition.field_ref:type_name -> trapperkeeper.sensor.v1.FieldPath
	0,  // 13: trapperkeeper.sensor.v1.ConditionValue.null_value:type_name -> trapperkeeper.sensor.v1.NullValue
	11, // 14: trapperkeeper.sensor.v1.ConditionValue.string_array:type_name -> trapperkeeper.sensor.v1.StringArray
	12, // 15: trapperkeeper.sensor.v1.ConditionValue.numeric_array:type_name -> trapperkeeper.sensor.v1.NumericArray
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_trapperkeeper_sensor_v1_rule_proto_init() }
func file_trapperkeeper_sensor_v1_rule_proto_init() {
	if File_trapperkeeper_sensor_v1_rule_proto != nil {
		return
	}
	file_trapperkeeper_sensor_v1_field_path_proto_init()
	file_trapperkeeper_sensor_v1_rule_proto_msgTypes[3].OneofWrappers = []any{
		(*ConditionValue_StringValue)(nil),
		(*ConditionValue_NumericValue)(nil),
		(*ConditionValue_BooleanValue)(nil),
		(*ConditionValue_NullValue)(nil),
		(*ConditionValue_StringArray)(nil),
		(*ConditionValue_NumericArray)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trapperkeeper_sensor_v1_rule_proto_rawDesc), len(file_trapperkeeper_sensor_v1_rule_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trapperkeeper_sensor_v1_rule_proto_goTypes,
		DependencyIndexes: file_trapperkeeper_sensor_v1_rule_proto_depIdxs,
		EnumInfos:         file_trapperkeeper_sensor_v1_rule_proto_enumTypes,
		MessageInfos:      file_trapperkeeper_sensor_v1_rule_proto_msgTypes,
	}.Build()
	File_trapperkeeper_sensor_v1_rule_proto = out.File
	file_trapperkeeper_sensor_v1_rule_proto_goTypes = nil
	file_trapperkeeper_sensor_v1_rule_proto_depIdxs = nil
}
