// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: trapperkeeper/sensor/v1/sensor_api.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SensorAPI_SyncRules_FullMethodName    = "/trapperkeeper.sensor.v1.SensorAPI/SyncRules"
	SensorAPI_ReportEvents_FullMethodName = "/trapperkeeper.sensor.v1.SensorAPI/ReportEvents"
)

// SensorAPIClient is the client API for SensorAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SensorAPI provides gRPC communication between sensors and TrapperKeeper server.
type SensorAPIClient interface {
	// SyncRules fetches active rules matching sensor tags.
	// ETAG-based: server returns 304 Not Modified if rules unchanged since last sync.
	SyncRules(ctx context.Context, in *SyncRulesRequest, opts ...grpc.CallOption) (*SyncRulesResponse, error)
	// ReportEvents submits a batch of events from sensor to server.
	// Batching reduces RPC overhead; max batch size enforced server-side.
	ReportEvents(ctx context.Context, in *ReportEventsRequest, opts ...grpc.CallOption) (*ReportEventsResponse, error)
}

type sensorAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSensorAPIClient(cc grpc.ClientConnInterface) SensorAPIClient {
	return &sensorAPIClient{cc}
}

func (c *sensorAPIClient) SyncRules(ctx context.Context, in *SyncRulesRequest, opts ...grpc.CallOption) (*SyncRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncRulesResponse)
	err := c.cc.Invoke(ctx, SensorAPI_SyncRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorAPIClient) ReportEvents(ctx context.Context, in *ReportEventsRequest, opts ...grpc.CallOption) (*ReportEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportEventsResponse)
	err := c.cc.Invoke(ctx, SensorAPI_ReportEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SensorAPIServer is the server API for SensorAPI service.
// All implementations must embed UnimplementedSensorAPIServer
// for forward compatibility.
//
// SensorAPI provides gRPC communication between sensors and TrapperKeeper server.
type SensorAPIServer interface {
	// SyncRules fetches active rules matching sensor tags.
	// ETAG-based: server returns 304 Not Modified if rules unchanged since last sync.
	SyncRules(context.Context, *SyncRulesRequest) (*SyncRulesResponse, error)
	// ReportEvents submits a batch of events from sensor to server.
	// Batching reduces RPC overhead; max batch size enforced server-side.
	ReportEvents(context.Context, *ReportEventsRequest) (*ReportEventsResponse, error)
	mustEmbedUnimplementedSensorAPIServer()
}

// UnimplementedSensorAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSensorAPIServer struct{}

func (UnimplementedSensorAPIServer) SyncRules(context.Context, *SyncRulesRequest) (*SyncRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncRules not implemented")
}
func (UnimplementedSensorAPIServer) ReportEvents(context.Context, *ReportEventsRequest) (*ReportEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportEvents not implemented")
}
func (UnimplementedSensorAPIServer) mustEmbedUnimplementedSensorAPIServer() {}
func (UnimplementedSensorAPIServer) testEmbeddedByValue()                   {}

// UnsafeSensorAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SensorAPIServer will
// result in compilation errors.
type UnsafeSensorAPIServer interface {
	mustEmbedUnimplementedSensorAPIServer()
}

func RegisterSensorAPIServer(s grpc.ServiceRegistrar, srv SensorAPIServer) {
	// If the following call panics, it indicates UnimplementedSensorAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SensorAPI_ServiceDesc, srv)
}

func _SensorAPI_SyncRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorAPIServer).SyncRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorAPI_SyncRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorAPIServer).SyncRules(ctx, req.(*SyncRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorAPI_ReportEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorAPIServer).ReportEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorAPI_ReportEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorAPIServer).ReportEvents(ctx, req.(*ReportEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SensorAPI_ServiceDesc is the grpc.ServiceDesc for SensorAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SensorAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trapperkeeper.sensor.v1.SensorAPI",
	HandlerType: (*SensorAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncRules",
			Handler:    _SensorAPI_SyncRules_Handler,
		},
		{
			MethodName: "ReportEvents",
			Handler:    _SensorAPI_ReportEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trapperkeeper/sensor/v1/sensor_api.proto",
}
