// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: trapperkeeper/sensor/v1/sensor_api.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventStatus int32

const (
	EventStatus_EVENT_STATUS_UNSPECIFIED EventStatus = 0
	EventStatus_EVENT_STATUS_ACCEPTED    EventStatus = 1
	EventStatus_EVENT_STATUS_REJECTED    EventStatus = 2
	EventStatus_EVENT_STATUS_ERROR       EventStatus = 3
)

// Enum value maps for EventStatus.
var (
	EventStatus_name = map[int32]string{
		0: "EVENT_STATUS_UNSPECIFIED",
		1: "EVENT_STATUS_ACCEPTED",
		2: "EVENT_STATUS_REJECTED",
		3: "EVENT_STATUS_ERROR",
	}
	EventStatus_value = map[string]int32{
		"EVENT_STATUS_UNSPECIFIED": 0,
		"EVENT_STATUS_ACCEPTED":    1,
		"EVENT_STATUS_REJECTED":    2,
		"EVENT_STATUS_ERROR":       3,
	}
)

func (x EventStatus) Enum() *EventStatus {
	p := new(EventStatus)
	*p = x
	return p
}

func (x EventStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_trapperkeeper_sensor_v1_sensor_api_proto_enumTypes[0].Descriptor()
}

func (EventStatus) Type() protoreflect.EnumType {
	return &file_trapperkeeper_sensor_v1_sensor_api_proto_enumTypes[0]
}

func (x EventStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventStatus.Descriptor instead.
func (EventStatus) EnumDescriptor() ([]byte, []int) {
	return file_trapperkeeper_sensor_v1_sensor_api_proto_rawDescGZIP(), []int{0}
}

type SyncRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []string               `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRulesRequest) Reset() {
	*x = SyncRulesRequest{}
	mi := &file_trapperkeeper_sensor_v1_sensor_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRulesRequest) ProtoMessage() {}

func (x *SyncRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trapperkeeper_sensor_v1_sensor_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRulesRequest.ProtoReflect.Descriptor instead.
func (*SyncRulesRequest) Descriptor() ([]byte, []int) {
	return file_trapperkeeper_sensor_v1_sensor_api_proto_rawDescGZIP(), []int{0}
}

func (x *SyncRulesRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type SyncRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*Rule                `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	Etag          string                 `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRulesResponse) Reset() {
	*x = SyncRulesResponse{}
	mi := &file_trapperkeeper_sensor_v1_sensor_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRulesResponse) ProtoMessage() {}

func (x *SyncRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trapperkeeper_sensor_v1_sensor_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRulesResponse.ProtoReflect.Descriptor instead.
func (*SyncRulesResponse) Descriptor() ([]byte, []int) {
	return file_trapperkeeper_sensor_v1_sensor_api_proto_rawDescGZIP(), []int{1}
}

func (x *SyncRulesResponse) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *SyncRulesResponse) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

type ReportEventsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Events          []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	SensorId        string                 `protobuf:"bytes,2,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	ClientTimestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=client_timestamp,json=clientTimestamp,proto3" json:"client_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReportEventsRequest) Reset() {
	*x = ReportEventsRequest{}
	mi := &file_trapperkeeper_sensor_v1_sensor_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportEventsRequest) ProtoMessage() {}

func (x *ReportEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trapperkeeper_sensor_v1_sensor_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportEventsRequest.ProtoReflect.Descriptor instead.
func (*ReportEventsRequest) Descriptor() ([]byte, []int) {
	return file_trapperkeeper_sensor_v1_sensor_api_proto_rawDescGZIP(), []int{2}
}

func (x *ReportEventsRequest) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ReportEventsRequest) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *ReportEventsRequest) GetClientTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ClientTimestamp
	}
	return nil
}

type ReportEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*EventResult         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	AcceptedCount int32                  `protobuf:"varint,2,opt,name=accepted_count,json=acceptedCount,proto3" json:"accepted_count,omitempty"`
	RejectedCount int32                  `protobuf:"varint,3,opt,name=rejected_count,json=rejectedCount,proto3" json:"rejected_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportEventsResponse) Reset() {
	*x = ReportEventsResponse{}
	mi := &file_trapperkeeper_sensor_v1_sensor_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportEventsResponse) ProtoMessage() {}

func (x *ReportEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trapperkeeper_sensor_v1_sensor_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportEventsResponse.ProtoReflect.Descriptor instead.
func (*ReportEventsResponse) Descriptor() ([]byte, []int) {
	return file_trapperkeeper_sensor_v1_sensor_api_proto_rawDescGZIP(), []int{3}
}

func (x *ReportEventsResponse) GetResults() []*EventResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ReportEventsResponse) GetAcceptedCount() int32 {
	if x != nil {
		return x.AcceptedCount
	}
	return 0
}

func (x *ReportEventsResponse) GetRejectedCount() int32 {
	if x != nil {
		return x.RejectedCount
	}
	return 0
}

type EventResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Status        EventStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=trapperkeeper.sensor.v1.EventStatus" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResult) Reset() {
	*x = EventResult{}
	mi := &file_trapperkeeper_sensor_v1_sensor_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResult) ProtoMessage() {}

func (x *EventResult) ProtoReflect() protoreflect.Message {
	mi := &file_trapperkeeper_sensor_v1_sensor_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResult.ProtoReflect.Descriptor instead.
func (*EventResult) Descriptor() ([]byte, []int) {
	return file_trapperkeeper_sensor_v1_sensor_api_proto_rawDescGZIP(), []int{4}
}

func (x *EventResult) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventResult) GetStatus() EventStatus {
	if x != nil {
		return x.Status
	}
	return EventStatus_EVENT_STATUS_UNSPECIFIED
}

func (x *EventResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetDiagnosticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SensorId      string                 `protobuf:"bytes,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiagnosticsRequest) Reset() {
	*x = GetDiagnosticsRequest{}
	mi := &file_trapperkeeper_sensor_v1_sensor_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiagnosticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiagnosticsRequest) ProtoMessage() {}

func (x *GetDiagnosticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trapperkeeper_sensor_v1_sensor_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiagnosticsRequest.ProtoReflect.Descriptor instead.
func (*GetDiagnosticsRequest) Descriptor() ([]byte, []int) {
	return file_trapperkeeper_sensor_v1_sensor_api_proto_rawDescGZIP(), []int{5}
}

func (x *GetDiagnosticsRequest) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

type GetDiagnosticsResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	BufferedEventsCount int32                  `protobuf:"varint,1,opt,name=buffered_events_count,json=bufferedEventsCount,proto3" json:"buffered_events_count,omitempty"`
	RulesSyncedCount    int32                  `protobuf:"varint,2,opt,name=rules_synced_count,json=rulesSyncedCount,proto3" json:"rules_synced_count,omitempty"`
	LastSyncTime        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_sync_time,json=lastSyncTime,proto3" json:"last_sync_time,omitempty"`
	ActiveRuleIds       []string               `protobuf:"bytes,4,rep,name=active_rule_ids,json=activeRuleIds,proto3" json:"active_rule_ids,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetDiagnosticsResponse) Reset() {
	*x = GetDiagnosticsResponse{}
	mi := &file_trapperkeeper_sensor_v1_sensor_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiagnosticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiagnosticsResponse) ProtoMessage() {}

func (x *GetDiagnosticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trapperkeeper_sensor_v1_sensor_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiagnosticsResponse.ProtoReflect.Descriptor instead.
func (*GetDiagnosticsResponse) Descriptor() ([]byte, []int) {
	return file_trapperkeeper_sensor_v1_sensor_api_proto_rawDescGZIP(), []int{6}
}

func (x *GetDiagnosticsResponse) GetBufferedEventsCount() int32 {
	if x != nil {
		return x.BufferedEventsCount
	}
	return 0
}

func (x *GetDiagnosticsResponse) GetRulesSyncedCount() int32 {
	if x != nil {
		return x.RulesSyncedCount
	}
	return 0
}

func (x *GetDiagnosticsResponse) GetLastSyncTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSyncTime
	}
	return nil
}

func (x *GetDiagnosticsResponse) GetActiveRuleIds() []string {
	if x != nil {
		return x.ActiveRuleIds
	}
	return nil
}

var File_trapperkeeper_sensor_v1_sensor_api_proto protoreflect.FileDescriptor

const file_trapperkeeper_sensor_v1_sensor_api_proto_rawDesc = "" +
	"\n" +
	"(trapperkeeper/sensor/v1/sensor_api.proto\x12\x17trapperkeeper.sensor.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\"trapperkeeper/sensor/v1/rule.proto\x1a#trapperkeeper/sensor/v1/event.proto\"&\n" +
	"\x10SyncRulesRequest\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags\"\\\n" +
	"\x11SyncRulesResponse\x123\n" +
	"\x05rules\x18\x01 \x03(\v2\x1d.trapperkeeper.sensor.v1.RuleR\x05rules\x12\x12\n" +
	"\x04etag\x18\x02 \x01(\tR\x04etag\"\xb1\x01\n" +
	"\x13ReportEventsRequest\x126\n" +
	"\x06events\x18\x01 \x03(\v2\x1e.trapperkeeper.sensor.v1.EventR\x06events\x12\x1b\n" +
	"\tsensor_id\x18\x02 \x01(\tR\bsensorId\x12E\n" +
	"\x10client_timestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0fclientTimestamp\"\xa4\x01\n" +
	"\x14ReportEventsResponse\x12>\n" +
	"\aresults\x18\x01 \x03(\v2$.trapperkeeper.sensor.v1.EventResultR\aresults\x12%\n" +
	"\x0eaccepted_count\x18\x02 \x01(\x05R\racceptedCount\x12%\n" +
	"\x0erejected_count\x18\x03 \x01(\x05R\rrejectedCount\"\x8b\x01\n" +
	"\vEventResult\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12<\n" +
	"\x06status\x18\x02 \x01(\x0e2$.trapperkeeper.sensor.v1.EventStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"4\n" +
	"\x15GetDiagnosticsRequest\x12\x1b\n" +
	"\tsensor_id\x18\x01 \x01(\tR\bsensorId\"\xe4\x01\n" +
	"\x16GetDiagnosticsResponse\x122\n" +
	"\x15buffered_events_count\x18\x01 \x01(\x05R\x13bufferedEventsCount\x12,\n" +
	"\x12rules_synced_count\x18\x02 \x01(\x05R\x10rulesSyncedCount\x12@\n" +
	"\x0elast_sync_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\flastSyncTime\x12&\n" +
	"\x0factive_rule_ids\x18\x04 \x03(\tR\ractiveRuleIds*y\n" +
	"\vEventStatus\x12\x1c\n" +
	"\x18EVENT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15EVENT_STATUS_ACCEPTED\x10\x01\x12\x19\n" +
	"\x15EVENT_STATUS_REJECTED\x10\x02\x12\x16\n" +
	"\x12EVENT_STATUS_ERROR\x10\x032\xd5\x02\n" +
	"\tSensorAPI\x12d\n" +
	"\tSyncRules\x12).trapperkeeper.sensor.v1.SyncRulesRequest\x1a*.trapperkeeper.sensor.v1.SyncRulesResponse\"\x00\x12m\n" +
	"\fReportEvents\x12,.trapperkeeper.sensor.v1.ReportEventsRequest\x1a-.trapperkeeper.sensor.v1.ReportEventsResponse\"\x00\x12s\n" +
	"\x0eGetDiagnostics\x12..trapperkeeper.sensor.v1.GetDiagnosticsRequest\x1a/.trapperkeeper.sensor.v1.GetDiagnosticsResponse\"\x00B\xf7\x01\n" +
	"\x1bcom.trapperkeeper.sensor.v1B\x0eSensorApiProtoP\x01ZJgithub.com/solatis/trapperkeeper/internal/protobuf/trapperkeeper/sensor/v1\xa2\x02\x03TSX\xaa\x02\x17Trapperkeeper.Sensor.V1\xca\x02\x17Trapperkeeper\\Sensor\\V1\xe2\x02#Trapperkeeper\\Sensor\\V1\\GPBMetadata\xea\x02\x19Trapperkeeper::Sensor::V1b\x06proto3"

var (
	file_trapperkeeper_sensor_v1_sensor_api_proto_rawDescOnce sync.Once
	file_trapperkeeper_sensor_v1_sensor_api_proto_rawDescData []byte
)

func file_trapperkeeper_sensor_v1_sensor_api_proto_rawDescGZIP() []byte {
	file_trapperkeeper_sensor_v1_sensor_api_proto_rawDescOnce.Do(func() {
		file_trapperkeeper_sensor_v1_sensor_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trapperkeeper_sensor_v1_sensor_api_proto_rawDesc), len(file_trapperkeeper_sensor_v1_sensor_api_proto_rawDesc)))
	})
	return file_trapperkeeper_sensor_v1_sensor_api_proto_rawDescData
}

var file_trapperkeeper_sensor_v1_sensor_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_trapperkeeper_sensor_v1_sensor_api_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_trapperkeeper_sensor_v1_sensor_api_proto_goTypes = []any{
	(EventStatus)(0),               // 0: trapperkeeper.sensor.v1.EventStatus
	(*SyncRulesRequest)(nil),       // 1: trapperkeeper.sensor.v1.SyncRulesRequest
	(*SyncRulesResponse)(nil),      // 2: trapperkeeper.sensor.v1.SyncRulesResponse
	(*ReportEventsRequest)(nil),    // 3: trapperkeeper.sensor.v1.ReportEventsRequest
	(*ReportEventsResponse)(nil),   // 4: trapperkeeper.sensor.v1.ReportEventsResponse
	(*EventResult)(nil),            // 5: trapperkeeper.sensor.v1.EventResult
	(*GetDiagnosticsRequest)(nil),  // 6: trapperkeeper.sensor.v1.GetDiagnosticsRequest
	(*GetDiagnosticsResponse)(nil), // 7: trapperkeeper.sensor.v1.GetDiagnosticsResponse
	(*Rule)(nil),                   // 8: trapperkeeper.sensor.v1.Rule
	(*Event)(nil),                  // 9: trapperkeeper.sensor.v1.Event
	(*timestamppb.Timestamp)(nil),  // 10: google.protobuf.Timestamp
}
var file_trapperkeeper_sensor_v1_sensor_api_proto_depIdxs = []int32{
	8,  // 0: trapperkeeper.sensor.v1.SyncRulesResponse.rules:type_name -> trapperkeeper.sensor.v1.Rule
	9,  // 1: trapperkeeper.sensor.v1.ReportEventsRequest.events:type_name -> trapperkeeper.sensor.v1.Event
	10, // 2: trapperkeeper.sensor.v1.ReportEventsRequest.client_timestamp:type_name -> google.protobuf.Timestamp
	5,  // 3: trapperkeeper.sensor.v1.ReportEventsResponse.results:type_name -> trapperkeeper.sensor.v1.EventResult
	0,  // 4: trapperkeeper.sensor.v1.EventResult.status:type_name -> trapperkeeper.sensor.v1.EventStatus
	10, // 5: trapperkeeper.sensor.v1.GetDiagnosticsResponse.last_sync_time:type_name -> google.protobuf.Timestamp
	1,  // 6: trapperkeeper.sensor.v1.SensorAPI.SyncRules:input_type -> trapperkeeper.sensor.v1.SyncRulesRequest
	3,  // 7: trapperkeeper.sensor.v1.SensorAPI.ReportEvents:input_type -> trapperkeeper.sensor.v1.ReportEventsRequest
	6,  // 8: trapperkeeper.sensor.v1.SensorAPI.GetDiagnostics:input_type -> trapperkeeper.sensor.v1.GetDiagnosticsRequest
	2,  // 9: trapperkeeper.sensor.v1.SensorAPI.SyncRules:output_type -> trapperkeeper.sensor.v1.SyncRulesResponse
	4,  // 10: trapperkeeper.sensor.v1.SensorAPI.ReportEvents:output_type -> trapperkeeper.sensor.v1.ReportEventsResponse
	7,  // 11: trapperkeeper.sensor.v1.SensorAPI.GetDiagnostics:output_type -> trapperkeeper.sensor.v1.GetDiagnosticsResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_trapperkeeper_sensor_v1_sensor_api_proto_init() }
func file_trapperkeeper_sensor_v1_sensor_api_proto_init() {
	if File_trapperkeeper_sensor_v1_sensor_api_proto != nil {
		return
	}
	file_trapperkeeper_sensor_v1_rule_proto_init()
	file_trapperkeeper_sensor_v1_event_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trapperkeeper_sensor_v1_sensor_api_proto_rawDesc), len(file_trapperkeeper_sensor_v1_sensor_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trapperkeeper_sensor_v1_sensor_api_proto_goTypes,
		DependencyIndexes: file_trapperkeeper_sensor_v1_sensor_api_proto_depIdxs,
		EnumInfos:         file_trapperkeeper_sensor_v1_sensor_api_proto_enumTypes,
		MessageInfos:      file_trapperkeeper_sensor_v1_sensor_api_proto_msgTypes,
	}.Build()
	File_trapperkeeper_sensor_v1_sensor_api_proto = out.File
	file_trapperkeeper_sensor_v1_sensor_api_proto_goTypes = nil
	file_trapperkeeper_sensor_v1_sensor_api_proto_depIdxs = nil
}
