
on: [push]

name: CI

jobs:
  build_and_test:
    name: build_and_test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Rust version check
        shell: bash
        run: |
          cargo --version
          rustc --version

      # - name: Install diesel cli
      #   run: cargo install diesel_cli --no-default-features --features sqlite

      # - name: Create tables & schema
      #   run: diesel migration run

      - name: Run trapperkeeper_tests
        run: cargo test

      - name: Build trapperkeeper
        run: cargo build --release --all-features
