
on: [push]

name: CI

env:
  DATABASE_URL: "sqlite:default.sqlite"

jobs:
  build_and_test:
    name: build_and_test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Rust version check
        shell: bash
        run: |
          cargo --version
          rustc --version

      - name: Install sqlx cli
        run: cargo install sqlx-cli --features sqlite

      - name: Run trapperkeeper_tests
        run: |
          sqlx db create
          sqlx migrate run
          cargo test

      - name: Build trapperkeeper
        run: cargo build --release --all-features
